language: go
sudo: false
go:
  - 1.5.4
  - 1.6.3
  - 1.7.1
  - tip
install:
  - go get -v github.com/qedus/osmpbf
script:
  - go test -v -covermode=count -coverprofile=profile.cov
after_success:
  - go get -v github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin
  - goveralls -coverprofile=profile.cov -service=travis-ci
